name: Build and Deploy Aleph Kintsu Node to AWS 

on: [ push ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential curl git clang libclang-dev pkg-config libssl-dev protobuf-compiler
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source "$HOME/.cargo/env"

    - name: Clone Aleph Node Repository
      run: git clone https://github.com/Cardinal-Cryptography/aleph-node.git

    - name: Build Aleph Node
      run: |
        cd aleph-node
        rustup show
        rustup target add x86_64-unknown-linux-gnu wasm32-unknown-unknown
        cargo build --release

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: dylan167/kintsu-testnet-azero:latest
